//https://hackerrank-challenge-pdfs.s3.amazonaws.com/2532-solve-me-first-English?AWSAccessKeyId=AKIAJ4WZFDFQTZRGO3QA&Expires=1562477783&Signature=EB7sQlpUlMxgnpNyyZmMr%2BKpL2w%3D&response-content-disposition=inline%3B%20filename%3Dsolve-me-first-English.pdf&response-content-type=application%2Fpdf
#include <cmath>
#include <cstdio>
#include <vector>
#include <iostream>
#include <algorithm>
using namespace std;

int solveMeFirst(int a, int b) {
 // Hint: Type return a+b; below:
  return a+b;
}

int main() {
  int num1, num2;
  int sum;
  cin>>num1>>num2;
  sum = solveMeFirst(num1,num2);
  cout<<sum;
  return 0;
}
